fn main() {
    panic!("Unrecoverable error which crashes the app at runtime!");
}
